### ISSUE TITLE
About the NPM package enwind

### ISSUE THREAD

**Issue by yekta** [b-kelly/enwind#1]
Hey, we have an inquiry about the NPM package "enwind". Is there an email we can reach out to you to talk?

**Comment by b-kelly** [comment]
@yekta Thank you for reaching out. In a (probably misguided) attempt to deter bots and spammers, I'd rather not directly post an email address here. However, my npm contact address does appear in my package's metadata. You can view the field via the following command:

```sh
npm view enwind maintainers
```

**Comment by yekta** [comment]
@b-kelly I've sent an email but couldn't get an answer. Maybe it got lost in your inbox?
